### ISSUE TITLE
Lage importfunksjonalitet for historiske donasjoner i adminpanel

### ISSUE THREAD

**Issue by Sodville** [stiftelsen-effekt/effekt-admin#100]

**Comment by Mofoss** [comment]
Får du tid til å se på dette, @Sodville? Det hadde vært gull om vi fikk alt dette unnagjort i oktober, før giversesongen overtar alt fokus! =)  @AndreasII

**Comment by fellmirr** [comment]
@JorgenLjones Det er gjort en del arbeid her på å implementere funksjonalitet i selve adminpanelet. Vegard var egentlig nesten helt i mål, og hadde gjort en god jobb. Problemet er at nå er den koden i ganske usync med det vi bruker i main, bla. grunnet en medium refactor.

Jeg mener det fornuftige å gjøre her, er å lukke dette kortet og kaste arbeidet som er gjort. Så kan vi heller fokusere på å lage et program / script som legger in data som vi er sikre på er rett. Mye av den jobben Vegard gjorde handlet om matching av donasjoner vi er usikre på hvem tilhører. Siden donasjonsvolumet på de historiske donasjonene er forholdsvis begrenset (jeg tipper det er under 1000 som vi ikke kan ha en garantert match på), foreslår jeg å punche dem manuelt. Litt kjedelig er det jo, men jeg tror det er raskere enn å bruke betydelig utviklingsressurser på det.

Tanker?

**Comment by JorgenLjones** [comment]
Enig.
