### ISSUE TITLE
Go through all tables and set more appropriate default width on individual columns

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/effekt-admin#152]
Some columns should be fitted to the content, others like name and email should have a reasonable width. Consider having the column header on two lines if it save width. Example: "Antall donasjoner" would save a lot of space if it's two lines:
Antall
donasjoner
Especially since the content in this column is small.

Relevant lists:
- [x] Donors
- [x] Donors' individual page (Donations, Distributions, AvtaleGiro and Vipps)
- [x] Distributions
- [x] Distribution individual page (Donations)
- [x] Donations
- [x] Vipps agreements
- [x] Vipps agreement charges
- [x] AvtaleGiro
- [x] Import logs

**Comment by fellmirr** [comment]
Go over and finish up with @JorgenLjones

**Comment by herleik** [comment]
Where's import logs?

**Comment by JorgenLjones** [comment]
Is there anything I can help with this issue? @herleik did you find the import logs under Logs?
