### ISSUE TITLE
Add often used quick buttons for date ranges

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/effekt-admin#192]
Add some buttons for quickly filter certain useful date ranges in all relevant tabs
- [ ] Last year
- [ ] This year (YTD)
- [ ] Last month
- [ ] This month

**Comment by jacobwulffwold** [comment]
@JorgenLjones Last month/year = last calender month(February)/year(2021) right? Not last 365(3/3/2021->today)/30 (3/2/2022 ->today) days

**Comment by JorgenLjones** [comment]
Yes, last calendar year and month is the most relevant interval

**Comment by xim** [comment]
I'll give it a whack!

**Comment by fellmirr** [comment]
#247
