### ISSUE TITLE
In the individual donor view, show their response(s) to referral question

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/effekt-admin#206]

**Comment by xim** [comment]
@JorgenLjones, Should this simply be a listing of individual answers, e.g. `["Avis", "Bekjent", "Moralfilosofisk tankeeksperiment som trengte et konkret eksempel for å fullføres."]` or do you want a table with answer, date, active flag, website session and the kitchen sink?

**Comment by xim** [comment]
I'll make a table, since some answers are super long

**Comment by JorgenLjones** [comment]
Me and Håkon just discussed this. How about adding a tab for these answers so that we can support an arbitrary number of answers as well as viably showing long sentences?
![image](https://user-images.githubusercontent.com/12774906/185337424-4352ce5e-9239-4415-aa25-5989259c12b2.png)

Putting the tab to the very right would also be nice
