### ISSUE TITLE
Add a section to Home with overview of transaction costs

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/effekt-admin#208]
Transaction costs include payments with Bank w/KID, AvtaleGiro, Vipps, Vipps w/KID and Vipps Recurring.

Section should include:
- [ ] Total transaction costs current month this year
- [ ] Total transaction costs current month last year to date
- [ ] Total transaction costs previous month this year
- [ ] Total transaction costs previous month last year
- [ ] Total transaction costs this year
- [ ] Total transaction costs last year to this date
- [ ] Bonus/Nice to have: Percentage change in parenthesis for each current year number, compared to last years' number

**Comment by mishra-ankit** [comment]
Based on discussion with @JorgenLjones, we decided to - 

> Total transaction costs previous month this year
> Total transaction costs previous month last year
Should show "NA" or "-" during month of January
