### ISSUE TITLE
☆ Review functionality for adding Vipps u/KID donations by CSV in AdminPanel

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/effekt-admin#233]
Should be prioritized before Smørekoppens fundraiser in October.
Some existing (legacy?) functionality is in place already. Only need some tweaking?

**Comment by JorgenLjones** [comment]
@fellmirr , have you been working on this? Smørekoppen did their fundraiser on Friday (101k raised!) and Ruth need this functionality ASAP ZULU

**Comment by fellmirr** [comment]
Unclear what the issue here has been, but this worked as intended for smørekoppen. #43 is the relevant issue for allowing the administration to create matching rules themselves.
