### ISSUE TITLE
Add solution to import Bank u/KID Fiken reports directly to AdminPanel

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/effekt-admin#234]
Today we upload the Fiken file to the collection spreadsheet, KID are assigned manually according to some specific rules and seldom unknown donation is handled somehow, then the list is exported to CSV and uploaded to AdminPanelet through Bank custom. This issue is about skipping the collection spreadsheet step, automating the rule based KID assignation and give the adminpanel user tools to handle those donations who need attention and import everything.

**Comment by fellmirr** [comment]
Closed as duplicate
