### ISSUE TITLE
Populate the table in the Donor tab like Distribution, Donation and the other tables

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/effekt-admin#267]
When first loading the Donor tab there table is empty, unlike the behavior in the tables in the Distribution, Donation and the other tabs. This inconsistent behavior is somewhat confusing.

**Comment by fellmirr** [comment]
A good thing to do here is probably to restructure the way this table works. Itd be better if it was structured in the same way as donations, agreements etc. with filters for searching.

Right now its a general component used for selecting donors for inserting single donations, just blown up and pasted on the page.
![Screenshot 2022-08-19 at 14 47 05](https://user-images.githubusercontent.com/693641/185621739-ac595544-f011-43f5-b5f3-2fe2b9f71509.png)
![Screenshot 2022-08-19 at 14 47 24](https://user-images.githubusercontent.com/693641/185621750-83a3abe8-315e-4f81-90a1-b8b04de17d5e.png)

This is the same component as the page.

![Screenshot 2022-08-19 at 14 47 34](https://user-images.githubusercontent.com/693641/185621791-aedacb5e-10e6-4241-9fce-56ffa875edf8.png)
