### ISSUE TITLE
Fix missing Donor data for payment list in individual AG agreement view

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/effekt-admin#272]
Donor name given on top of page, but donor name is missing in list of associated donations
![Image](https://user-images.githubusercontent.com/12774906/185916724-ba716652-04b0-4891-afd2-52dd3e47368f.png)

**Comment by fellmirr** [comment]
If it's easy to remove Donor, method and KID from the table do so. If not, fix the missing fields.

**Comment by xim** [comment]
Fixed in PR #293
