### ISSUE TITLE
Stopped Vipps agreement counter dont work on Home tab

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/effekt-admin#292]

**Comment by xim** [comment]
There are a lot of NULL values for `cancellation_date`, and last date with a cancellation is in October. Not sure what to make of that.

**Comment by philiphand** [comment]
**Small update but no solution:**

I created and stopped a new agreement today, which seems to have worked fine. The agreement is now counted as a stopped agreement on the home tab, and the record was automatically updated with the cancellation date in the database.

That doesn't explain the other agreements lacking a cancellation date, though. 

I'm not sure what the cause could be, but it does seem unlikely that no agreements were cancelled in November, as seven agreements were cancelled in October.

**Comment by fellmirr** [comment]
Closing as it seems to be fixed, likely a bug we fixed in the autumn.
