### ISSUE TITLE
Bug on AdminPanel: Faulty counting of stopped Vipps agreements

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/effekt-admin#329]
Five stopped agreements so far in January, to a value of 2 030 kr
![Image](https://user-images.githubusercontent.com/12774906/212385480-72c0a4fe-28f2-4faf-89e5-bd9383e45c9f.png)

But when listing the individual stopped agreements so far this year, it's only three (or four if expired counts), and the sum does not match 2 030 kr
![Image](https://user-images.githubusercontent.com/12774906/212385721-0e6fc00b-c774-46f1-8a9d-743145f2e49f.png)

**Comment by EliseAndresen** [comment]
Håkon suspects this is no longer the case, will look into it.
