### ISSUE TITLE
Feil ved opplasting av Paypal-donasjoner.

### ISSUE THREAD

**Issue by AndreasII** [stiftelsen-effekt/effekt-admin#75]
Etter at jeg trykker på knappen "Process" går det ca. 1 minutt, og så får jeg opp følgende feilmelding:

![bilde](https://user-images.githubusercontent.com/51961744/62414011-c3154e80-b616-11e9-8bdd-3d2512f0e62d.png)

Hvis jeg heller prøver å laste opp 

en helt anenn fil (som åpenbart ikke fungerer) får jeg en umiddelbar feilmelding som sier at filformatet er feil (eller noe sånt).

Vipps-opplasting ser ut til å fungere fint.

[Download.txt](https://github.com/stiftelsen-effekt/effekt-admin/files/3464015/Download.txt)

Aktuell fil er vedlagt (men bytt filnavn fra .txt til .csv, jeg fikk ikke lov til å laste opp en csv-fil).

Jeg prøvde også å endre fra komma til semikolon, uten hell.

**Comment by fellmirr** [comment]
Dette viste seg å handle om at Paypal starter sine CSV filer med en såkalt Byte Order Mark (BOM), som måtte strippes vekk før filen kunne behandles. Tok litt tid å trace, fikset nå.
