### ISSUE TITLE
Som bruker skal jeg gjennom en enkel spørring kunne få kun de donasjonene gått til EAN sine administrerte kontoer

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/effekt-admin#90]
Databasen må på en eller annen måte tracke de donasjoner som har kommet inn gjennom EAN sine Vipps-nummer, PayPal og bankkonto. Dette behøver vi for å kunne få aggregert informasjon om total innsamlet til EAN sine kontoer i en gitt periode, i tillegg til de samlede tilknyttede gebyrene og andel driftsdonasjoner. I dag registreres feks donasjoner til Effekt sin PayPal og til EAN sin PayPal likt.

Å ha slik funksjonalitet er essensielt for regnskapet til EA Norge og for å finne ut hvor mye penger EA Norge skal tildele til Effekt hvert kvartal. Første gang dette skjer er i starten av desember 2019.

**Comment by fellmirr** [comment]
Allerede implementert i sheets
