### ISSUE TITLE
I starten av desember kan EA Norge få tilstrekkelig oversikt fra databasen til å beregne korrekt tildeling til Effekt for forrige kvartal.

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/effekt-admin#91]
Vi trenger da at databasen kan gi ut totalt innsamlet til EAN sine kontoer gjennom Vipps, PayPal og Bank (med og uten KID), hvor mye vi har betalt i gebyrer for disse donasjonene og hvor stor andel av disse donasjonene som var øremerket som driftsdonasjoner.

#90 er relevant her

**Comment by fellmirr** [comment]
Allerede implementert i google sheets
