### ISSUE TITLE
Ved opplasting av Vipps-donasjon bestemmer skriptet automatisk hvem som eier dataen ved å sjekke celle B2 eller B3 i opplastet .csv-fil.

### ISSUE THREAD

**Issue by AndreasII** [stiftelsen-effekt/effekt-admin#93]
For å unngå problem i framtiden med å laste inn data i databasen med feil eier, kan man sjekke dette automtisk i CSV-filen i Vipps-importen.

I teorien vil vi aldri importere PayPal for EAN, så da trenger bare valget for eier å styre import av bankdata (noe vi ikke gjør i dag for Effekt-bankdata, men kan tenkes at vi starter med).

**Comment by fellmirr** [comment]
@JorgenLjones Jeg husker ikke helt hva som er greia her, er dette i praksis et kort vi kan arkivere?

**Comment by JorgenLjones** [comment]
Har spurt Andreas om han husker

**Comment by AndreasII** [comment]
@fellmirr @JorgenLjones 
Før lastet vi opp Vipps-filer for både nytt (EAN) og gammelt system (StiftEff). Hvis jeg husker rett skilte ikke import-funksjonen på hvem som eide dataene, og det var ikke mulig å velge det ved import. Jeg måtte derfor manuelt endre donasjonene fra EAN til StiftEff etter hver import.

Nå importerer vi ikke lengre fra gammel Vipps-løsning, så oppgaven lukkes .
