### ISSUE TITLE
Beholde desimaler ved OCR-import

### ISSUE THREAD

**Issue by AndreasII** [stiftelsen-effekt/effekt-admin#94]
Når man importerer donasjoner fra bank ved å laste opp OCR-filer blir ikke desimaler registrert. Se Donation_ID 1795 for eksempel. Dette er egentlig en donasjon på kr 52,90, ikke kr 53,-

Vi må rette opp import-rutinen.

**Comment by Mofoss** [comment]
Jeg ser nå hvorfor dette blir feil; variabelen "sum_confirmed" i Donations-tabellen i databasen er en INTEGER ("int(11)"). Ikke en en decimal, slik som .feks. transaction_cost er

**Comment by fellmirr** [comment]
Det har du nok helt rett i Eirk. Underlig, det skal heldigvis bare være å bytte til decimal. Jeg tester på dev :)

**Comment by fellmirr** [comment]
@Mofoss Tror du det byr på noen problemer for importen til sheets om jeg endrer typen? Det fungerer helt smertefritt på backend, så eneste er om det skaper trøbbel for deg :)

Hvis ikke bare bytter jeg, så er problemet løst.

**Comment by Mofoss** [comment]
Ingen problemer for Sheets om du bytter! Så bare kjør på :)
