### ISSUE TITLE
Donasjonskvittering - legge til flere detaljer. 

### ISSUE THREAD

**Issue by Mofoss** [stiftelsen-effekt/effekt-admin#97]
Mer spesifikt dato for donasjonen (siden kvitteringer kommer en stund senere) og donasjonskanal.

**Comment by Mofoss** [comment]
Håkon, får du til å legge til donasjonskanal også? Se bilde under etter at jeg donerte med Vipps etter oppdateringen din. Ettersom det tar litt tid så tenker jeg det er fint. Kan f.eks. legges til som detalj:

"Vi mottok din donasjon 26.12 2019 12:00 **gjennom [Vipps/PayPal/bankoverføring]**"

Dessuten er tidspunktet ikke riktig, tror jeg. Det står 13:07 på min Vipps. Muligens er "12:00" bare default? Dette er ikke viktig, og hvis det bare er litt feil så er det fint. Men med bank blir det vel f.eks. helt feil? Jeg tenker at dato (ikke tidspunkt) er nok om det er enklere.

FYI @AndreasII 

![image](https://user-images.githubusercontent.com/17338692/71641155-2976c980-2ca8-11ea-91b0-73cf5fd727e9.png)

**Comment by AndreasII** [comment]
Vet ikke om vi heller burde lage et eget kort på dette, men jeg har laget en PDF med en rekke endringsforslag til donasjonskvitteringen. 

Hvis du vil kan jeg lage et kort og legge til disse som to-do-punkter i kortet, @fellmirr.

[Kommentarer e-post.pdf](https://github.com/stiftelsen-effekt/effekt-admin/files/4014068/Kommentarer.e-post.pdf)

**Comment by fellmirr** [comment]
Vi kan legge til donasjonskanal også ja. 

Jeg innser nå at tidspunkt er dumt å ta med, ettersom vipps ikke rapporterer tidspunkt på donasjoner. Mao. Er det riktig som du sier at 12:00 bare er default.
Jeg endrer det til dato, så er det mindre forvirrende (og renere uansett).
