### ISSUE TITLE
Legge til mulighet for å slette donorer fra databasen

### ISSUE THREAD

**Issue by AndreasII** [stiftelsen-effekt/effekt-admin#98]
Vi har mange donorer i databasen som bare er lagt inn som test. 

Dersom det er mulig hadde det vært fin å kunne slette disse donorene (manuelt), for å rydde opp, og lettere kunne ha oversikt over antall donorer.

**Comment by Mofoss** [comment]
Jeg kan fikse dette. Det må nødvendigvis også bety sletting av deres KID-nummer også

**Comment by Mofoss** [comment]
@AndreasII, det er veldig sjeldent det er tydelige test eller tullregistreringer. Det fungerer å slette dem, hvis man også sletter KID. Men 1) det koster ingenting å ha dem i DBen, 2) hva om noen faktisk donerer med en brukt KID senere?

Jeg ser ingen grunn til at vi skal drive å slette. Evt först om lenge, at vi kan for personvernhensyn ta og slette alle KIDr og donorIDer som ikke har donert etter f.eks 1 eller 2 år. Enig? I så fall kan du bare lukke denne

**Comment by AndreasII** [comment]
Ok. Jeg tenkte at det blir mye klutter, og lange lister i Google Sheets som gjør ting tregere og mindre oversiktlig. 

Men det er foreløpig ikke et problem, sp da lar vi det bare være sånn.

For donorer som anonymiseres kan vi bare endre navn på donoren.
